# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: audio_streaming.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'audio_streaming.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x61udio_streaming.proto\x12\x05\x61udio\"r\n\x0b\x41udioPacket\x12\x13\n\x0bpacket_data\x18\x01 \x01(\x0c\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\x12\x17\n\x0fsequence_number\x18\x03 \x01(\x05\x12\x18\n\x10\x61lgorithm_delay\x18\x04 \x01(\x05\"\"\n\x0eStreamResponse\x12\x16\n\x0estatus_message\x18\x01 \x01(\t2M\n\x0e\x41udioStreaming\x12;\n\x0bStreamAudio\x12\x12.audio.AudioPacket\x1a\x15.audio.StreamResponse\"\x00(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'audio_streaming_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUDIOPACKET']._serialized_start=32
  _globals['_AUDIOPACKET']._serialized_end=146
  _globals['_STREAMRESPONSE']._serialized_start=148
  _globals['_STREAMRESPONSE']._serialized_end=182
  _globals['_AUDIOSTREAMING']._serialized_start=184
  _globals['_AUDIOSTREAMING']._serialized_end=261
# @@protoc_insertion_point(module_scope)
